### ISSUE TITLE
ใช้ Firebase Firestore ได้มั้ยครับ

### ISSUE THREAD

**Issue by saranpol** [devmountaintechfest/Mr.fox-devhack#1]
อันนี้ require ให้ไป dev ต่อกับ stack เดิม หรือว่าอยากให้สร้างระบบใหม่เลยมั้ยครับ

**Comment by saranpol** [comment]
=====================
Firebase Firestore uses gRPC (Google Remote Procedure Call) for communication between client-side applications and the Firestore servers. gRPC is a modern open-source high-performance Remote Procedure Call (RPC) framework developed by Google that is based on Protocol Buffers, a language-agnostic binary serialization format.

gRPC provides several benefits over traditional REST APIs, including efficient serialization and deserialization of data, support for bi-directional streaming, and efficient error handling. These features make gRPC an excellent choice for real-time and high-throughput applications like Firebase Firestore.

Additionally, gRPC provides SDKs for a wide range of programming languages, which makes it easy for developers to build applications that communicate with Firebase Firestore using their preferred language.

=====================
Firebase Firestore has a built-in caching system that helps to improve application performance by reducing the number of network requests required to access data.

Firestore's client-side SDKs implement a local cache that automatically stores query results in memory, enabling fast read operations without the need for network round trips. The cache is updated in real-time whenever the data in the Firestore backend changes, ensuring that the client always has the latest data.

Firestore's cache is particularly useful in offline scenarios, where a device is not connected to the internet. In such cases, the local cache is used to serve data to the application, providing a seamless offline experience.

Firestore's caching system can be configured to suit different use cases. For example, you can configure the cache to automatically evict data that has not been accessed for a certain period to reduce memory usage. You can also set cache behavior for individual queries, specifying whether or not the results should be cached and for how long.

Overall, Firestore's caching system is a powerful feature that enables developers to build fast, responsive applications that work well even in offline scenarios.

**Comment by saranpol** [comment]
ผมใส่ code ใน fork ที่ทำหน้าที่คล้ายๆ TODO list (สร้าง trade diary) ไปให้ดูนะครับ
ตอนแรกผมทำเว็บนี้เล่นๆ กับพี่กิ๊บศรีสยาม แต่ว่าเหมือนไม่ได้ทำอะไรต่อ ก็เลยเอามาเป็นตัวอย่างให้ดูวิธีการ dev ของผมนะครับ
หน้าตาเว็บก็ประมาณๆ นี้
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/61673/221420640-4eb95e45-862c-4b85-a8f2-5b227c2a10ca.png">

**Comment by annibuliful** [comment]
อยากทให้สร้างใหม่เลยครับเพราะจะได้เข้าใจการใช้งานมากขึ้นครับ

**Comment by saranpol** [comment]
โอเค ถ้าตามเวลาที่มีผมคงมีโชวแค่นี้ละครับ ^/\\^ (อยากช่วยพี่คิงให้ mrfox ปังๆ นะครับ)
